spring.web.resources.add-mappings=true
server.port=8080
spring.mvc.view.suffix =.html
security.basic.enabled=false
management.security.enabled=false
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=neranga@neotechsys.info
spring.mail.password=Senu@215465
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.from=noreply@myemail.com
management.endpoints.web.exposure.include= health
spring.security.user.password=admin
spring.security.user.roles=ADMIN
spring.datasource.url=jdbc:h2:mem:testdb1;DB_CLOSE_ON_EXIT=TRUE;MODE=MySQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.path=/h2
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.h2.console.enabled=true
spring.h2.console.settings.trace=true
spring.h2.console.settings.web-allow-others=true
security.headers.frame=false
spring.sql.init.schema-locations=classpath:/schema.sql
spring.kafka.bootstrap-servers=quote-msg.servicebus.windows.net:9093
spring.kafka.client-id=first-producer

# Kafka properties for SASL authentication
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://quote-msg.servicebus.windows.net/;SharedAccessKeyName=msg;SharedAccessKey=Y26IESaywKLI8AVUamluySzX8Aa8NvBVd+AEhHGJr6c=;EntityPath=quote-msg";
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.security.protocol=SASL_SSL

# Consumer configurations
spring.kafka.consumer.group-id=$Default
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.targa.labs.dev.kafkaonazure.SimpleMessage




#spring.datasource.username=neo
#spring.datasource.password=
#spring.datasource.url=jdbc:sqlserver://neo-app.database.windows.net:1433;database=chat_app;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#spring.jpa.show-sql = true
